config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]
  resources :books do
    resources :words
    resource :bookmarks, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'search','quiz_index'
    end
    resource :quiz, only: [:new, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :genre_id, numericality: { other_than: 1, message: 'を選択してください' }

  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :words, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '用語' },
    { id: 3, name: 'データベース' },
    { id: 4, name: 'HTML/CSS' },
    { id: 5, name: 'JavaScript' },
    { id: 6, name: 'Ruby' },
    { id: 7, name: 'PHP' },
    { id: 8, name: 'Python' },
    { id: 9, name: 'Java' },
    { id: 10, name: 'C#' },
    { id: 11, name: 'Swift' }
  ]

  include ActiveHash::Associations
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :password_confirmation, on: :create
    validates :profile
    validates :birth_date
  end
  validates :email, uniqueness: true
  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'を半角英数字で入力してください' }, on: :create

  has_many :books
  has_many :words
  has_many :comments
  has_many :bookmarks
  has_many :bookmarked_books, through: :bookmarks, source: :book
end

app/models/word.rb
class Word < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :info
  end

  belongs_to :user
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_book, only: [:create, :destroy]

  def show
    @user = current_user
    @books = @user.bookmarked_books.order(created_at: :DESC)
  end

  def create
    bookmark = current_user.bookmarks.build(book_id: params[:book_id])
    bookmark.save
  end

  def destroy
    bookmark = Bookmark.find_by(book_id: params[:book_id], user_id: current_user.id)
    bookmark.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :search_book, only: [:search, :quiz_index]

  def index
    @books = Book.all.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @book.save
      redirect_to new_book_word_path(@book.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = '削除が完了しました'
    redirect_to action: :index
  end

  def search
  end

  def quiz_index
  end

  private

  def book_params
    params.require(:book).permit(:title, :genre_id, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user != @book.user
  end

  def search_book
    @q = Book.ransack(params[:q])
    @results = @q.result.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment_book, only: [:index, :create, :destroy]

  def index
    @comment = Comment.new
    @comments = @book.comments.includes(:user).order(created_at: :DESC)
  end

  def create
    @comment = @book.comments.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to action: :index
    else
      @comments = @book.comments.includes(:user).order(created_at: :DESC)
      render :index
    end
  end

  def destroy
    comment = @book.comments.find(params[:id])
    comment.destroy
    redirect_to action: :index
  end

  private

  def set_comment_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @quizzes = @book.words.order('RAND()').limit(10)
  end

  def show
    @book = Book.find(params[:book_id])
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  def after_sign_in_path_for(_resource)
    books_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(created_at: :DESC)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word_book, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_word, only: [:edit, :update, :destroy]
  before_action :move_to_home, only: [:new, :create, :edit, :update, :destroy]

  def index
    @words = @book.words.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def new
    @word = Word.new
  end

  def create
    @word = @book.words.new(word_params)
    if @word.valid?
      @word.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update(word_params)
      redirect_to book_words_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    redirect_to action: :index
  end

  def show
    @user = current_user
    @words = @user.words.order(created_at: :DESC)
    @books = @user.books
  end

  private

  def set_word_book
    @book = Book.find(params[:book_id])
  end

  def set_word
    @word = @book.words.find(params[:id])
  end

  def move_to_home
    redirect_to controller: :books, action: :index if current_user.id != @book.user_id
  end

  def word_params
    params.require(:word).permit(:name, :info).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/quizzes/new.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="words">
        <div class="word-index-header">
          <div class="quit-quiz-wrap">
            <%= link_to 'テストを中断する', quiz_index_books_path, class: "quit-quiz" %>
          </div>
          <div class="word-book-info">
            <div class="word-book-title"><%= strip_tags(@book.title).truncate(10) %></div>
            <div class="word-book-genre"><%= @book.genre.name %></div>
            <div class="word-book-user"><%= "by #{@book.user.nickname}" %></div>
          </div>
        </div>
        <div class="quiz-wrap">
          <% @quizzes.each do |quiz| %>
            <div class="quiz">
              <div class='container'>
                <div class='flip_box'>
                  <div class='front'>
                    <div class="word-content">
                      <div class="quiz-name">
                        <%= quiz.name %>
                      </div>
                      <div class="quiz-btn-wrap">
                        <div class="answer-btn" id="correct">◯</div>
                        <div class="answer-btn" id="incorrect">×</div>
                      </div>
                    </div>
                  </div>
                  <div class='back'>
                    <div class="quiz-back-content">
                      <div class="quiz-info">
                        <%= quiz.info %>
                      </div>
                    </div>
                  </div>
                </div>
                <div class='r_wrap'>
                  <div class='s_round'>
                    <div class='s_arrow'>→</div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          <% if @quizzes.present? %>
            <div class="grade-wrap">
              <%= link_to '採点する！', book_quiz_path(@book.id), class: "grade" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/quizzes/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="words">
        <div class="word-index-header">
          <div class="quit-quiz-wrap">
          </div>
          <div class="word-book-info">
            <div class="word-book-title"><%= strip_tags(@book.title).truncate(10) %></div>
            <div class="word-book-genre"><%= @book.genre.name %></div>
            <div class="word-book-user"><%= "by #{@book.user.nickname}" %></div>
          </div>
        </div>
        <div class="quiz-wrap">
          <div class="quiz-result">
            <div class="pie-chart" id="blue-circle"></div>
            <div class="pie-chart" id="gray-circle"></div>
            <div class="circle">
              <div class="data-percent">5/10</div>
            </div>
          </div>
          <div class="grade-wrap">
            <%= link_to 'テストを終了する', quiz_index_books_path, class: "grade" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>