config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]
  resources :books do
    resources :words
    resource :bookmarks, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'search','quiz_index'
    end
    resource :quiz, only: [:new, :show]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :book
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment_book, only: [:index, :create, :destroy]

  def index
    @comment = Comment.new
    @comments = @book.comments.includes(:user).order(created_at: :DESC)
  end

  def create
    @comment = @book.comments.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to action: :index
    else
      @comments = @book.comments.includes(:user).order(created_at: :DESC)
      render :index
    end
  end

  def destroy
    comment = @book.comments.find(params[:id])
    comment.destroy
    redirect_to action: :index
  end

  private

  def set_comment_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>

      <div class="comment">
        <div class="comment-wrap">
          <div class="comment-header">
            <%= link_to truncate(("＜ #{@book.title}"), length: 10), book_path(@book.id), class: "back-show" %>
            <div class="comment-title">
              <b class="comment-title-text">
                コメント
              </b>
            </div>
          </div>

          <div class="comment-note">
            <p class="comment-note-text">
              相手のことを考え丁寧なコメントを心がけましょう。
            </p>
          </div>

          <div class="comments">
            <% @comments.each do |comment| %>
              <div class="comment-unit">
                <div class="upper-comment">
                  <div class="comment-user">
                    <%= comment.user.nickname %>
                  </div>
                  <div class="comment-date">
                    <%= l(comment.created_at, format: :long) %>
                  </div>
                  <% if user_signed_in? && comment.user_id == current_user.id %>
                    <%= link_to '送信取消', book_comment_path(comment.book.id, comment.id), method: :delete, class: "comment-destroy" %>
                  <% end %>
                </div>
                <div class="lower-comment">
                  <div class="comment-content">
                    <%= safe_join("#{comment.content}".split("\n"),tag(:br)) %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>

          <div class="comment-form">
            <%= form_with model: [@book, @comment], url: book_comments_path(@book.id), method: :post, local: true do |f| %>
              <%= f.text_area :content, class: "form-input", placeholder: "コメントを入力する", maxlength: 200 %>
              <%= f.submit "送信", class: "form-submit" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>