config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]
  resources :books do
    resources :words
    resource :bookmarks, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'search','quiz_index'
    end
    resource :quiz, only: [:new, :show]
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :genre_id, numericality: { other_than: 1, message: 'を選択してください' }

  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :words, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :search_book, only: [:search, :quiz_index]

  def index
    @books = Book.all.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @book.save
      redirect_to new_book_word_path(@book.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = '削除が完了しました'
    redirect_to action: :index
  end

  def search
  end

  def quiz_index
  end

  private

  def book_params
    params.require(:book).permit(:title, :genre_id, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user != @book.user
  end

  def search_book
    @q = Book.ransack(params[:q])
    @results = @q.result.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="new-book">
        <div class="new-book-text">
          ブックを編集する
        </div>
        <%= render partial: "layouts/form_book", locals: { book: @book } %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="books">
        <div class="to-newbook">
          <div class="breadcrumbs">
            <%= 'ホーム' %>
          </div>
          <%= link_to 'New book', new_book_path, class: "to-newbook-text" %>
        </div>
        <div class="delete-notice">
          <%= flash[:notice] %>
        </div>
        <div class="book-wrap">
          <%= render partial: "layouts/book", collection: @books %>
        </div>
        <div class="pagenation">
          <%= paginate @books %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="new-book">
        <div class="new-book-text">
          ブックを作成する
        </div>
        <%= render partial: "layouts/form_book", locals: { book: @book } %>
      </div>
    </div>
  </div>
</div>

app/views/books/quiz_index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="books">
        <div class="search-wrap">
          <div class="breadcrumbs">
            <%= 'テスト' %>
          </div>
          <div class="search-rightwrap">
            <div class="search-note">※ジャンルを選択してください</div>
            <%= search_form_for @q, url: quiz_index_books_path, class: "search-form" do |form| %>
              <%= form.search_field :title_cont, placeholder: "   検索する", class: "search-input" %>
              <%= form.select :genre_id_eq, options_from_collection_for_select(Genre.all, :id, :name) %>
              <%= form.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
        </div>
        <div class="book-wrap">
          <% @results.each do |book| %>
            <% if book.words.present?%>
              <div class="book">
                <div class="book-content">
                  <%= image_tag book.image.variant(resize: '400x350'), class: "book-image" if book.image.attached? %>
                  <div class="book-title">
                    <%= book.title %>
                  </div>
                  <div class="book-genre">
                    <%= book.genre.name %>
                  </div>
                </div>
                <div class="book-subcontent">
                  <div class="book-date">
                    <%= l(book.created_at, format: :long) %>
                  </div>
                  <div class="book-user">
                    <%= "by #{book.user.nickname}" %>
                  </div>
                </div>
                <%= link_to new_book_quiz_path(book.id), class: "quiz-cover" do %>
                  <div>
                    テストする
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
        <div class="pagenation">
          <%= paginate @results %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/search.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="books">
        <div class="search-wrap">
          <div class="breadcrumbs">
            <%= '検索' %>
          </div>
          <div class="search-rightwrap">
            <div class="search-note">※ジャンルを選択してください</div>
            <%= search_form_for @q, url: search_books_path, class: "search-form" do |form| %>
              <%= form.search_field :title_cont, placeholder: "   検索する", class: "search-input" %>
              <%= form.select :genre_id_eq, options_from_collection_for_select(Genre.all, :id, :name) %>
              <%= form.submit "検索", class: "search-btn" %>
            <% end %>
          </div>
        </div>
        <div class="book-wrap">
          <%= render partial: "layouts/book", collection: @results, as: "book" %>
        </div>
        <div class="pagenation">
          <%= paginate @results %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "layouts/side-bar" %>
  </div>
  <div class="main">
    <div class="main-wrap">
      <%= render "layouts/header" %>
      <div class="show-book-wraps">
        <%# ブックを作成したユーザーにのみ表示する %>
        <div class="breadcrumbs-show">
          <div class="breadcrumbs-wrap">
            <%= link_to 'ホーム', books_path, class: "breadcrumbs" %>
            <%= "＞ ブック詳細" %>
          </div>
          <div class="to-editbook">
          <% if user_signed_in? && current_user == @book.user %>
            <%= link_to 'Edit', edit_book_path(@book.id), class: "to-newbook-text" %>
            <%= link_to 'Delete', book_path(@book.id), method: :delete, class: "to-newbook-text" %>
          <% end %>
          </div>
        </div>
        <div class="show-book-wrap">
          <div class="book-header">
            <% if @book.words.present? %>
              <%= link_to "ワード(#{@book.words.count})", book_words_path(@book.id), class: "book-header-text" %>
            <% else %>
              <div class="book-header-text">ワード(0)</div>
            <% end %>
          </div>
          <%= render partial: "layouts/book", locals:{ book: @book } %>
        </div>
      </div>
    </div>
  </div>
</div>