config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { registrations: 'users/registrations',
                                    sessions: 'users/sessions' }
  resources :users, only: [:index, :show]
  resources :books do
    resources :words
    resource :bookmarks, only: [:show, :create, :destroy]
    resources :comments, only: [:index, :create, :destroy]
    collection do
      get 'search','quiz_index'
    end
    resource :quiz, only: [:new, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :genre_id, numericality: { other_than: 1, message: 'を選択してください' }

  belongs_to :user
  has_one_attached :image, dependent: :destroy
  has_many :words, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user.id).exists?
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true

  belongs_to :user
  belongs_to :book
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '用語' },
    { id: 3, name: 'データベース' },
    { id: 4, name: 'HTML/CSS' },
    { id: 5, name: 'JavaScript' },
    { id: 6, name: 'Ruby' },
    { id: 7, name: 'PHP' },
    { id: 8, name: 'Python' },
    { id: 9, name: 'Java' },
    { id: 10, name: 'C#' },
    { id: 11, name: 'Swift' }
  ]

  include ActiveHash::Associations
  has_many :books
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :password_confirmation, on: :create
    validates :profile
    validates :birth_date
  end
  validates :email, uniqueness: true
  validates :password, format: { with: /\A[a-zA-Z0-9]+\z/, message: 'を半角英数字で入力してください' }, on: :create

  has_many :books
  has_many :words
  has_many :comments
  has_many :bookmarks
  has_many :bookmarked_books, through: :bookmarks, source: :book
end

app/models/word.rb
class Word < ApplicationRecord
  with_options presence: true do
    validates :name
    validates :info
  end

  belongs_to :user
  belongs_to :book
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_book, only: [:create, :destroy]

  def show
    @user = current_user
    @books = @user.bookmarked_books.order(created_at: :DESC)
  end

  def create
    bookmark = current_user.bookmarks.build(book_id: params[:book_id])
    bookmark.save
  end

  def destroy
    bookmark = Bookmark.find_by(book_id: params[:book_id], user_id: current_user.id)
    bookmark.destroy
  end

  private

  def set_book
    @book = Book.find(params[:book_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  before_action :move_to_index, only: [:edit, :update, :destroy]
  before_action :search_book, only: [:search, :quiz_index]

  def index
    @books = Book.all.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.valid?
      @book.save
      redirect_to new_book_word_path(@book.id)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    flash[:notice] = '削除が完了しました'
    redirect_to action: :index
  end

  def search
  end

  def quiz_index
  end

  private

  def book_params
    params.require(:book).permit(:title, :genre_id, :image).merge(user_id: current_user.id)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index if current_user != @book.user
  end

  def search_book
    @q = Book.ransack(params[:q])
    @results = @q.result.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment_book, only: [:index, :create, :destroy]

  def index
    @comment = Comment.new
    @comments = @book.comments.includes(:user).order(created_at: :DESC)
  end

  def create
    @comment = @book.comments.new(comment_params)
    if @comment.valid?
      @comment.save
      redirect_to action: :index
    else
      @comments = @book.comments.includes(:user).order(created_at: :DESC)
      render :index
    end
  end

  def destroy
    comment = @book.comments.find(params[:id])
    comment.destroy
    redirect_to action: :index
  end

  private

  def set_comment_book
    @book = Book.find(params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  def new
    @book = Book.find(params[:book_id])
    @quizzes = @book.words.order('RAND()').limit(10)
  end

  def show
    @book = Book.find(params[:book_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  def index
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.order(created_at: :DESC)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word_book, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_word, only: [:edit, :update, :destroy]
  before_action :move_to_home, only: [:new, :create, :edit, :update, :destroy]

  def index
    @words = @book.words.includes(:user).order(created_at: :DESC).page(params[:page]).per(10)
  end

  def new
    @word = Word.new
  end

  def create
    @word = @book.words.new(word_params)
    if @word.valid?
      @word.save
      redirect_to book_path(@book.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @word.update(word_params)
      redirect_to book_words_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @word.destroy
    redirect_to action: :index
  end

  def show
    @user = current_user
    @words = @user.words.order(created_at: :DESC)
    @books = @user.books
  end

  private

  def set_word_book
    @book = Book.find(params[:book_id])
  end

  def set_word
    @word = @book.words.find(params[:id])
  end

  def move_to_home
    redirect_to controller: :books, action: :index if current_user.id != @book.user_id
  end

  def word_params
    params.require(:word).permit(:name, :info).merge(user_id: current_user.id, book_id: params[:book_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_book.html.erb
<div class="book">
  <% if current_user.id == book.user_id %>
    <%= link_to book_path(book.id), class: "book-content" do %>
      <%= image_tag book.image.variant(resize: '400x350'), class: "book-image" if book.image.attached? %>
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-genre">
        <%= book.genre.name %>
      </div>
    <% end %>
  <% else %>
    <%= link_to book_words_path(book.id), class: "book-content" do %>
      <%= image_tag book.image.variant(resize: '400x350'), class: "book-image" if book.image.attached? %>
      <div class="book-title">
        <%= book.title %>
      </div>
      <div class="book-genre">
        <%= book.genre.name %>
      </div>
    <% end %>
  <% end %>
  <div class="book-subcontent">
    <div class="book-date">
      <%= l(book.created_at, format: :long) %>
    </div>
    <div class="book-user">
      <%= "by #{book.user.nickname}" %>
    </div>
  </div>
  <div class="book-cover">
    <div class="to-newword">
    <% if user_signed_in? && current_user == book.user %>
      <%= link_to image_tag("/IMG_1514.PNG", class: "to-new-word"), new_book_word_path(book.id) %>
    <% end %>
    </div>
    <%= link_to image_tag("/IMG_1516.PNG", class: "book-chat-log"), book_comments_path(book.id) %>
    <div id="bookmarks_buttons_<%= book.id %>">
       <%= render partial: 'bookmarks/bookmark', locals: { book: book } %>
    </div>
  </div>
</div>

app/views/layouts/_error-messages.html.erb
<% if model.errors.any? %>
  <div>
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_form_book.html.erb
<%= form_with model: book, local: true do |f| %>
  <%= render partial: 'layouts/error-messages', locals: { model: book }, class: "book-error-alert" %>
  <div class="book">
    <div class="book-content">
      <div class="book-form-text">
        <p>タイトル</p>
      </div>
      <%= f.text_area :title, class:"new-book-title", id:"book-title", placeholder:"タイトル（20文字まで)", maxlength:"20" %>
      <div class="book-form-text">
        <P>ジャンル</p>
      </div>
      <%= f.collection_select(:genre_id, Genre.all, :id, :name, {}, {class:"select-box", id:"book-genre"}) %>
      <div class="book-form-text">
        <P>画像</p>
      </div>
      <%= f.file_field :image, id:"item-image" %>
    </div>
    <div class='create-book-btn-wrap'>
      <%= f.submit "作成する", class: 'create-book-btn' %>
      <%= link_to "戻る", books_path, class: 'book-back-btn' %>
    </div>
  </div>
<% end %>

app/views/layouts/_form_word.html.erb
<%= form_with model: [book, word], local: true do |f| %>
  <%= render partial: 'layouts/error-messages', locals: { model: word }, class: "book-error-alert" %>
  <div class="new-word-content">
    <div class="new-word-content-text">
      <p>単語</p>
    </div>
    <%= f.text_area :name, class:"new-word-name", id:"book-title", placeholder:"単語（20文字まで)", maxlength:"20" %>
    <div class="new-word-content-text">
      <P>定義</p>
    </div>
    <%= f.text_area :info, class:"new-word-info", id:"book-title", placeholder:"定義（100文字まで)", maxlength:"100" %>
  </div>
  <div class='create-book-btn-wrap'>
    <%= f.submit "追加する", class: 'create-book-btn' %>
  </div>
  <%= link_to "戻る", book_path(book.id), class: 'back-btn' %>
<% end %>

app/views/layouts/_header.html.erb
<div class="header-wrap">
  <div class="left-header">
    <%= image_tag("/IMG_1476.png", class: "header-log") %>
  </div>
  <div class="right-header">
    <div class="to-mypage"><%= current_user.nickname %></div>
  </div>
</div>

app/views/layouts/_side-bar.html.erb
<div class="side-wrap">
  <div class="headline">
    <div class="headline-name">
      <%= link_to 'ホーム', books_path, class: "headline-name" %>
    </div>
  </div>
  <div class="headline">
    <div class="headline-name">
      <%= link_to '検索', search_books_path, class: "headline-name" %>
    </div>
  </div>
  <div class="headline">
    <div class="headline-name">
      <%= link_to 'テスト', quiz_index_books_path, class: "headline-name" %>
    </div>
  </div>
  <div class="headline">
    <div class="headline-name">
      <%= link_to 'マイページ', user_path(current_user.id), class: "headline-name" %>
    </div>
  </div>
</div>

app/views/layouts/_user.html.erb
<div class="user-info">
  <div class="upper">
    <div class="user-nickname">
      <%= user.nickname %>
    </div>
    <div class="user-edit">
      <div><%= link_to 'Edit', edit_user_registration_path(current_user.id), class: "user-edit-link" %></div>
      <div><%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "log-out" %></div>
    </div>
  </div>
  <div class="middle">
    <div class="user-profile">
      <%= user.profile %>
    </div>
  </div>
  <div class="lower">
    <%= link_to "books(#{Book.where(user_id: current_user.id).count})", user_path(current_user.id), class: "card-type-select" %>
    <% if user.words.present? %>
      <%= link_to "words(#{Word.where(user_id: current_user.id).count})", book_word_path(user.books.ids, user.words.ids), class: "card-type-select" %>
    <% else %>
      <div class="card-type-select">words(0)</div>
    <% end %>
    <% if user.bookmarked_books.present? %>
      <%= link_to "bookmarks(#{Bookmark.where(user_id: current_user.id).count})", book_bookmarks_path(user.bookmarked_books.ids), class: "card-type-select" %>
    <% else %>
      <div class="card-type-select">bookmarks(0)</div>
    <% end %>
  </div>
</div>

app/views/layouts/_word.html.erb
<div class="word">
  <div class="word-content">
    <div class="word-name">
      <%= word.name %>
    </div>
    <div class="word-info">
      <%= word.info %>
    </div>
    <div class="word-cover">
      <% if user_signed_in? && current_user == word.user %>
        <%= link_to image_tag("/IMG_1520.PNG", class: "to-edit-word"), edit_book_word_path(word.book.id, word.id) %>
        <%= link_to image_tag("/IMG_1521.PNG", class: "to-delete-word"), book_word_path(word.book.id, word.id), method: :delete %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>